# Coding Productivity
# ------------
- repo: wakatime/vim-wakatime
- repo: ruanyl/vim-gh-line
- repo: github/copilot.vim

# Golang related
- repo: fatih/vim-go
  if: has('nvim-0.4.0') || has('patch-8.0.1453')
  on_ft: [ go, gomod, gotexttmpl, gohtmltmpl ]
  hook_add: |-
    let g:go_gopls_enabled = 0
    let g:go_code_completion_enabled = 0
    let g:go_doc_keywordprg_enabled = 0
    let g:go_def_mapping_enabled = 0
    let g:go_jump_to_error = 0
    let g:go_fmt_autosave = 1
    let g:go_fmt_fail_silently = 1
    let g:go_imports_autosave = 1
    let g:go_mod_fmt_autosave = 0
    let g:go_snippet_engine = 'ultisnips'
    let g:go_textobj_enabled = 1
    let g:go_list_height = 10
    let g:go_list_autoclose = 0
    let g:go_fold_enable = []
    let g:go_info_mode = 'gopls'
    let g:go_def_mode = 'gopls'
    let g:go_referrers_mode = 'gopls'
    let g:go_implements_mode = 'guru'
    let g:go_highlight_array_whitespace_error = 0
    let g:go_highlight_chan_whitespace_error = 0
    let g:go_highlight_space_tab_error = 0
    let g:go_highlight_trailing_whitespace_error = 0
    let g:go_highlight_extra_types = 1
    let g:go_highlight_build_constraints = 1
    let g:go_highlight_fields = 1
    let g:go_highlight_format_strings = 1
    let g:go_highlight_functions = 1
    let g:go_highlight_function_calls = 1
    let g:go_highlight_function_parameters = 1
    let g:go_highlight_types = 1
    let g:go_highlight_generate_tags = 1
    let g:go_highlight_operators = 1
    let g:go_highlight_string_spellcheck = 0
    let g:go_highlight_variable_declarations = 0
    let g:go_highlight_variable_assignments = 0
    if has('nvim') || exists(':terminal')
      let g:go_term_enabled = 1
      let g:go_term_close_on_exit = 0
    endif
